### ISSUE TITLE
Issue While Opening Project

### ISSUE THREAD

**Issue by pranav2w** [GameInstitutes/RuntimeMeshLoader#1]
First of all thanks for plugin.

I am not able to start project while include RuntimeMeshLoader plugin.

I had made C++ blank project.Then made a new folder 'Plugins' and paste **RuntimeMeshLoader** in it.

When I am open my project get below error.
![error](https://user-images.githubusercontent.com/12233807/28170479-28eeaa94-6803-11e7-9487-961d2c7c619c.JPG)

After that I copied **Plugins\RuntimeMeshLoader-master\ThirdParty\assimp\bin\x64\** all files in my **Syetem32**
 
Now it is opening with out any error and I am able see plugin in my project.

But I am not able to get any node in my blueprint.

Can you tell how to load 3D model via blueprint?

**Comment by givemeyourshit** [comment]
where do you mean by system 32?
